# General default settings
[general_settings]
debug_mode = false
verbose_mode = true
timestamp = "%Y-%m-%d %H:%M:%S"

# Default backup settings
[backup.defaults]
source_directories = ["/Users/mikeearley/.config", "/Users/mikeearley/scripts"]
exclude_directories = ["/Users/mikeearley/scripts/.venv"]
backup_directory = "/Users/mikeearley/backup"
backup_prefix = "backup"
number_of_copies_to_keep = 2

# Default logging settings
[logging.defaults]
log_directory = "/Users/username/.config/backit/logs"
archive_directory = "/Users/username/.config/backit/logs/archive"
log_prefix = "backup"
log_retention_period = "1 week"
log_level = "INFO"
timestamp = "%Y-%m-%d %H:%M:%S:%f"
log_format = "<level> <icon> | <timestamp> | <message>"
color_setup = [
    {level = "TRACE", foreground = "<##03edf9>", background = "", style = "<bold>", icon = "🔍"},
    {level = "DEBUG", foreground = "<blue>", background = "", style = "<bold>", icon = "🐞"},
    {level = "INFO", foreground = "", background = "", style = "<bold>", icon = "ℹ️"},
    {level = "SUCCESS", foreground = "<green>", background = "<LIGHT-YELLOW>", style = "<bold>", icon = "✅"},
    {level = "WARNING", foreground = "<yellow>", background = "", style = "<bold>", icon = "⚠️"},
    {level = "ERROR", foreground = "<red>", background = "", style = "<bold>", icon = "❌"},
    {level = "CRITICAL", foreground = "", background = "<RED>", style = "<bold>", icon = "🔥"},
]
custom_levels = { custom_msg = { no = 27, color = "<fg #4e00ff>", icon = "🚀" } }

# Default Git settings
[git.defaults]
remote_repository = "https://github.com/mearleycf/backup.git"
default_branch = "main"
remote_name = "origin"

# Default Celery settings
[celery.defaults]
broker_url = "amqp://guest@localhost//"
result_backend = "rpc://"
frequency = "weekly"
schedule = { day_of_week = 0, hour = 8, minute = 30 }

# Additional miscellaneous settings
[misc.defaults]
lock_file_location = "/Users/mikeearley/.config/backit/locks/lockfile.lock"
timeout_value = 120  # Timeout for processes in seconds

# fish_config backup settings
[backup.job.fish_config]
    [backup.job.fish_config.backup]
    source_directories = ["/Users/mikeearley/.config/fish"]
    backup_directory = "/Users/mikearley/backup/fish_config"
    

    [backup.job.fish_config.logging]
    log_directory = "/Users/mikeearley/backup_logs/fish_config"
    archive_directory = "/Users/mikeearley/backup_logs/fish_config/archive"

    [backup.job.fish_config.git]
    remote_repository = "https://github.com/mikeearley/backup_fish_config.git"

    [backup.job.fish_config.celery]
    frequency = "daily"
    schedule = { day_of_week = 0, hour = 8, minute = 30 }

# screenshots backup settings
[backup.job.screenshots]
    [backup.job.screenshots.backup]
    source_directories = ["/Users/mikeearley/screenshots/"]
    backup_directory = "/Users/mikearley/backup/screenshots"

    [backup.job.screenshots.logging]
    log_directory = "/Users/mikeearley/backup_logs/screenshots"
    archive_directory = "/Users/mikeearley/backup_logs/screenshots/archive"
    
    [backup.job.screenshots.git]
    remote_repository = "https://github.com/mikeearley/backup_screenshots.git"

    [backup.job.screenshots.celery]
    frequency = "daily"
    schedule = { day_of_week = 0, hour = 8, minute = 30 }

    [backup.job.screenshots.misc]
    timeout_value = 600

